open-sauced/ai

README.md
Updated the project's readme with installation instructions and utility icons.
Closes #6 
Not needed.
=> docs: Updated the README.md

src/content-scripts/profileScreen.ts
This PR intends to resolve the bug introduced in https://github.com/open-sauced/browser-extensions/pull/14 due to the use of a top-level await by wrapping the awaited call in an async function.
Resolves #25.
Build process after the patch:
=> fix: Wrapped the await call in an async()

manifest.json, src/App.tsx, src/hooks/useAuth.ts, src/hooks/useOpensaucedUserCheck.ts, src/pages/home.tsx, src/pages/profile.tsx, src/pages/start.tsx, src/utils/cache.ts, src/utils/fetchOpenSaucedApiData.ts, tailwind.config.js
This PR add 2 pages to the extension popup/dropdown.
As written in the commit descriptions, here are the changes I made along with those two pages.
- Add tailwind plugin to centering tailwind divider, it can be found at `tailwind.config.cjs`. More often than not, tailwind divider would not be centered between elements, we need to specify padding corrections. therefore, I search the internet and found that plugin to simplify the proccess.
- Moving token retrieval to custom hooks so it can be used anywhere.
- add custom hooks to check current tab is github profile url and opensauced user
-  add activeTab permission to `manifest.json` to check url of current tab from extension popup (_this related to previous bullet point_)
- refactor routing logic to use `context api`, so it can be used …
=> feat: add home page and profile page

manifest.json, src/constants.ts, src/content-scripts/profileScreen.ts, src/utils/urlMatchers.ts, src/worker/background.ts
This PR updates the service worker with a `tabs.onUpdated` listener which checks for URL changes at `github.com` and notifies the content-script, resolving an issue with the profile page buttons mentioned in #35. 4aa584c7992c4c21d89c4ca98c6283d13cc905a5.
Additionally, 
* The regex used in [`getGithubUsername()`](https://github.com/open-sauced/browser-extensions/blob/6751fa55d65d5ab4b96b0d1d1fa3624780087e0f/src/utils/urlMatchers.ts#L1) has been updated to ensure that it only matches the username without any appended query parameters. 6751fa55d65d5ab4b96b0d1d1fa3624780087e0f.
* Adds a handler to the background worker to deal with any changes to the Supabase auth cookie. d4aa979d343ebab0c4c2ebc54a761ea5b8304f2e.
Resolves #35.
Before:
After 4aa584c7992c4c21d89c4ca98c6283d13cc905a5:
=> feat: GitHub page update listener

.github/workflows/release.yml, package.json
Should fix the issue where dist folder does not get attached to release assets. Works here - https://github.com/diivi/browser-extensions/releases
#42
=> fix: attach dist folder to release assets

src/content-scripts/components/InviteToOpenSauced/InviteToOpenSaucedButton.ts, src/content-scripts/components/InviteToOpenSauced/InviteToOpenSaucedModal.ts, src/content-scripts/components/ViewOnOpenSaucedButton/ViewOnOpenSaucedButton.ts, src/content-scripts/profileScreen.ts, src/utils/colorPreference.ts, src/utils/dom-utils/inviteToOpenSauced.ts, src/utils/dom-utils/viewOnOpenSauced.ts, tailwind.config.js
This PR adds light mode to [`InviteToOpenSaucedButton.ts`](https://github.com/open-sauced/browser-extensions/blob/6063bf18e67217348acb5fb5817a9b47db97d2ab/src/content-scripts/components/InviteToOpenSauced/InviteToOpenSaucedButton.ts), [`ViewOnOpenSaucedButton.ts`](https://github.com/open-sauced/browser-extensions/blob/6063bf18e67217348acb5fb5817a9b47db97d2ab/src/content-scripts/components/ViewOnOpenSaucedButton/ViewOnOpenSaucedButton.ts). A custom light mode color `gh-white` has been added to [`tailwind.config.js`](https://github.com/open-sauced/browser-extensions/blob/6063bf18e67217348acb5fb5817a9b47db97d2ab/tailwind.config.js#L16). 37e1c3a16461ba2eb021a4b9a051017343e0d29c.
Additionally [`InviteToOpenSaucedModal.ts`](https://github.com/open-sauced/browser-extensions/blob/6063bf18e67217348 …
=> feat: Added light mode to GH profile buttons

src/content-scripts/profileScreen.ts, src/utils/colorPreference.ts, src/utils/dom-utils/inviteToOpenSauced.ts, src/utils/dom-utils/viewOnOpenSauced.ts
This PR fixes the bug mentioned in #46 by adding a check for a pre-existing button before adding a new button into view. 03ef88cd5c00fe61a67ee33795cea4a5261855b2.
Additionally, this PR refactors the current GitHub color preference implementation to set the "dark" class globally for github.com if a dark theme is opted by the user in GH's appearance settings. This will be beneficial as it enables any new elements added to github.com to utilize the `dark:` variant for styling, ensuring consistency with the user's preferences. d0a709cf7f8c3e6361cf1d9547e1d7df97405585.
Resolves #46.
> When switching from the overview to the repositories tab, a duplicate "View on OpenSauced" Button gets added to the webpage.
=> fix: Duplicate buttons on GH profile page

.github/workflows/release.yml
This PR fixes the `set-output` deprecation warning during the `setup` job of the release workflow by updating the run script. A test run of the updated workflow without the warnings can be found here, https://github.com/Anush008/browser-extensions/actions/runs/4839263469.
Resolves #41.
Not applicable.
=> fix: set-output deprecation warning

vite.config.ts
This PR fixes the `⚠️ Unrecognized manifest key 'default'` error that arises after the installation of the extension by replacing the namespace import of the `manifest.json` file, https://github.com/open-sauced/browser-extensions/blob/a447551d46ea35dde6b674853ab55094728014c2/vite.config.ts#L4 with a default import. https://github.com/open-sauced/browser-extensions/blob/587293a85c69514cc48fc2122728cda7e63918d9/vite.config.ts#L4
=> fix: unrecognized-manifest-key error

.eslintrc.js, src/constants.ts, src/content-scripts/components/RepoVoting/RepoUnvoteButton.ts, src/content-scripts/components/RepoVoting/RepoVoteButton.ts, src/content-scripts/github.ts, src/utils/checkAuthentication.ts, src/utils/dom-utils/repoVotingButtons.ts, src/utils/fetchOpenSaucedApiData.ts, src/utils/urlMatchers.ts
* Adds a feature that allows users to vote/unvote for repos directly from GitHub, by checking if the user is logged in && the repo exists on opensauced. 
* If user has already voted repo, show the unvote button else show the vote button.
* The DOM-manipulation part is done, styling and voting/ removing votes remains.
#9
=> feat: vote repos

npm-shrinkwrap.json, package.json, src/constants.ts, src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts, src/pages/aiprdescription.tsx, src/utils/aiprdescription/configurationReducer.ts, src/utils/aiprdescription/cursorPositionInsert.ts, src/utils/aiprdescription/descriptionconfig.ts, src/utils/aiprdescription/openai.ts, src/utils/checkAuthentication.ts, src/utils/fetchGithubAPIData.ts
* This PR updates the AI PR description feature to use the new https://api.opensauced.pizza/v1/prs/description/generate endpoint. 
* The AI description page of the extension dropdown has been updated and the OpenAI token input has been removed. 
* The Description config types have been updated to reflect the new changes.
* A new function 
https://github.com/open-sauced/ai/blob/a5b7cddeec0d26e226aefcffd14e993dbb3b0b9b/src/utils/aiprdescription/cursorPositionInsert.ts#L2
has been added to emulate the typewriter effect from a string rather than a stream, since that's response from the API endpoint. The older function has been retained for future use.
Resolves #85.
=> feat: Updated to the new AI PR description endpoint

src/App.tsx, src/constants.ts, src/pages/help.tsx, src/pages/home.tsx, src/pages/resources.tsx
Add a new page "Resources" to the app with external links to Discussions and Issues.
The page can be accessed from the Home page. It contains a list of external links to Discussions and Issues. The Discussions and Issues links are displayed with an arrow icon and descriptive text. The Resources page also contains a back button to return to the Home page.
Fixes #96
https://github.com/open-sauced/ai/assets/36790357/0fb1d9f2-8990-4c44-b05a-8f2da6e9492d
=> feat: Resources page to link users to open-sauced feedback/discussions

src/constants.ts, src/content-scripts/components/AICodeRefactor/ChangeSuggestorButton.ts, src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts, src/content-scripts/github.ts, src/utils/aiprdescription/openai.ts, src/utils/dom-utils/changeSuggestorButton.ts, src/utils/dom-utils/prWatcher.ts, src/utils/urlMatchers.ts
In action (except the duplicate buttons):
I need to take care of some weird DOM-watching stuff; after that, this should be ready to merge.
The Generator button is disappearing randomly right now, maybe something to do with how the watcher is set up.
=> feat: generate code suggestions via AI

.github/workflows/release.yml
This PR updates the release workflow to use the latest version of actions/checkout and actions/setup-node. Node version is updated to 18.x. The open-sauced/release action is updated to v2.1.0.
The updated release-action bumps the `version` value in the `manfest.json` file after each release. 
A working demo of the updated workflow can be found here: https://github.com/Anush008/release-test/actions/runs/5075094479.
Manifest.json version bump demo commit: https://github.com/Anush008/release-test/commit/8b79587aa6aac9326d4e4a2033097b63b4cfa999.
Resolves #53.
=> feat: Manifest.json version bump

.github/workflows/release.yml, manifest.json
This PR fixes #121 by updating the open-sauced/release action version to `v2.1.1` which has been updated with a patch to bump the `version`  value of the `manifest.json` file when a release is done on the `main` branch with integer-only version numbers.
Additionally, the `version` value of the `manifest.json` file has been reset.
Patch: https://github.com/open-sauced/release/pull/14
Resolves #121.
=> fix: bump manifest version on main only

manifest.json, npm-shrinkwrap.json, package.json, src/constants.ts, src/pages/aiprdescription.tsx, src/pages/profile.tsx, src/pages/start.tsx, src/utils/checkAuthentication.ts, src/worker/background.ts
This PR includes three changes:
- Added an option to log out from the application.
- Limited the extension host permissions in the manifest.json file.
- Set the maximum description length to 500 characters. 
The utility functions added to support logout/login have been prefixed with `opt` to distinguish as auth-utility functions called  on explicit user actions and not on events like `onInstalled` or `onStartUp`. https://github.com/open-sauced/ai/blob/f08e2179cee33ef47ac05068c979db49b9bc0fd1/src/utils/checkAuthentication.ts#L45-L58
The max description length has been set to 500 in accordance to the API constraints.
https://github.com/open-sauced/api.opensauced.pizza/blob/e55f963aa4f3fda34440fc035d45776d244408eb/src/pull-requests/dtos/ …
=> feat: Logout from the extension

test/utils/urlMatcher.test.ts
This PR adds the tests for #142 
fix #142
=> test: add tests for utils/urlMatchers.ts

.gitignore, src/utils/checkAuthentication.ts, src/worker/background.ts, test/utils/checkAuthentication.test.ts
Adds tests for `checkAuthentication.ts`
@Anush008 can you check if everything still works? I mean your login and logout logic (and related stuff), I was able to log in and log out, but maybe I missed something.
I had to refactor checkAuthentication() to make it more pure and testable. Will cover more lines soon.
=> test: add tests for checkAuth.ts

src/content-scripts/github.ts, src/pages/help.tsx, src/vite-env.d.ts, vite.config.ts
This PR updates the help page to import the version from package.json instead of vite-env.d.ts. It also removes an unused variable from vite-env.d.ts and removes definition from vite.config.ts.
Resolves #156.
=> fix: undefined config during build

src/pages/home.tsx
This PR updates the Home page to display the user's login instead of their name in the Insights section. It also refactors the code to use the new login property in the Highlight interface. The link to the user's profile page now correctly uses the login property.
closes #160
=> feat: uses username on highlight instead of full name

src/content-scripts/components/AICodeRefactor/ChangeSuggestorButton.ts, src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts, src/pages/home.tsx, src/pages/posthighlight.tsx, src/ts/types.ts, src/utils/fetchOpenSaucedApiData.ts
* Resolves #131 by passing the PR URL without any query params or IDs. With this update,  appending `/commits` to the endpoint, the current inability to get commit messages of draft PRs mentioned at https://github.com/open-sauced/ai/pull/79#issuecomment-1552287192 will be resolved. https://github.com/open-sauced/ai/blob/b697b701b9c299e5b02ba13491e249e8dafae668/src/utils/fetchGithubAPIData.ts#L23-L24 d1429b6f4a747a3b6ff5c66695738b15954ce759.
* Resolves #153 by updating `href` to the configured domain. b6f1dd0b2e72e9e505e3ef8a10a258c7ad23382c.
* Resolves #119 by disabling the button events when the AI generation is underway. fc26ef8fdd6acfb1b0826d7773a2136e0e0a8bbb.
* Additionally, refactors the latest highlight feat, moves the `Highlights` type definition to the types file for reusability, …
=> fix: highlight redirection, multiple AI generation, draft commit messages

src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts, src/content-scripts/github.ts, src/hooks/useGithubPRPageCheck.ts, src/pages/home.tsx, src/pages/posthighlight.tsx, src/utils/fetchGithubAPIData.ts, src/utils/fetchOpenSaucedApiData.ts, src/utils/urlMatchers.ts, test/utils/urlMatcher.test.ts
This PR includes refactoring of the post highlight feature to remove message passing, removal of message listener from github.ts, and addition of tests for getPullRequestAPIURL() function. These changes improve the code quality and ensure better test coverage.
As mentioned before, message passing to a content-script is error-prone and should be avoided if possible.
=> refactor: removed post highlight message passing 

src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts
FIx for https://github.com/open-sauced/ai/pull/168#issuecomment-1577971689
It didn't work because descriptionConfig.enabled never existed.
We do this via sync storage now -[beta/src/utils/dom-utils/addDescriptionGenerator.ts#L18](https://github.com/open-sauced/ai/blob/beta/src/utils/dom-utils/addDescriptionGenerator.ts?rgh-link-date=2023-06-06T08%3A28%3A12Z#L18)
=> fix: remove configuration enabled check from AI button

src/popup/pages/posthighlight.tsx
This PR adds a toast promise to the generateAiDescription function in posthighlight.tsx. The toast promise displays a loading message wThis feedback would show the user a message if something went wrong while generating AI for post to highlight
This adds an error message feedback for user when they face an issue in the AI generation on the post to highight popup
This adds an error message feedback for user when they face an issue in the AI generation on the post to highight popup
#168 
While Generating: 
Successful message: 
Error Message:
=> chore: add a user feedback in case of an error

npm-shrinkwrap.json, package.json, src/popup.css, src/popup/components/HighlightSlide.tsx, src/popup/pages/aiprdescription.tsx, src/popup/pages/home.tsx, src/utils/fetchOpenSaucedApiData.ts
Might consider changing the scrollbar too:
This PR introduces a new carousel design for the highlights feed, ensuring uniform heights for a consistent look and feel. The new design enhances the user experience by providing a visually appealing and easy-to-use interface.
This looks like a major improvement imo, here are some edge cases (too big of a description and no title) that the earlier version could not handle too:
=> feat: carousel design for the highlights feed

src/constants.ts, src/popup/components/HighlightSlide.tsx, src/popup/pages/home.tsx, src/ts/types.ts, src/utils/fetchOpenSaucedApiData.ts
Fixes #161 and completes the highlights feed.
#161
=> feat: show highlight reactions

.eslintrc.js, vite.config.ts, vitest.config.ts
Fix for https://discordapp.com/channels/714698561081704529/928693344358514698/1121122996384432148, an issue where the build had not manifest.json because of incorrect vite config.
This PR updates the `.eslintrc.js` file to include `vitest.config.ts` in the `ignorePatterns` array. It also updates the `vite.config.ts` file to import `defineConfig` from `vite` instead of `vitest/config`. Additionally, it removes the `test` object from the `vite.config.ts` file and creates a new `vitest.config.ts` file to configure the testing environment.
=> fix: separate vite and vitest configs

src/popup/components/HighlightSlide.tsx, src/popup/pages/home.tsx, src/popup/pages/settings.tsx, src/utils/fetchOpenSaucedApiData.ts, tailwind.config.js, vite.config.ts
This PR introduces a new feature that allows users to react or unreact on highlights. It adds the necessary functionality to the React component, enabling users to interact with highlights and provide feedback. This feature enhances the user experience by providing a more interactive and engaging platform.
Fixes #195
=> feat: react/unreact on highlights

CHANGELOG.md, npm-shrinkwrap.json, package.json, src/utils/ai-utils/descriptionconfig.ts
This PR introduces a new feature that makes the default tone formal. It addresses issue #211 and can be found in commit [814378d](https://github.com/open-sauced/ai/commit/814378d4cbe31aa4c38ea1f8900c9f8bd3c97ae0).
=> main <- 1.11.0-beta.1 

src/constants.ts
Refactor SUPABASE_AUTH_COOKIE_NAME constant in constants.ts to remove the conditional check for the environment. The constant is now set to `sb-${import.meta.env.VITE_OPEN_SAUCED_SUPABASE_ID}-auth-token`. 
The auth cookie key of https://insights.opensauced.pizza has been updated to `sb-ibcwmlhcimymasokhgvn-auth-token`.
=> chore: Update auth cookie name for production

src/hooks/useGetGitHubPageInfo.ts, src/popup/pages/home.tsx, src/utils/fetchOpenSaucedApiData.ts
Add a button to the popup which redirects the user to the repo's page on insights.opensauced.
Given that it exists on opensauced.
#14
=> feat: view repos on opensauced

src/popup/pages/home.tsx, src/popup/pages/posthighlight.tsx, src/utils/fetchOpenSaucedApiData.ts
This PR redirects the users to the home page after creating a highlight.
Fixes #178
=> fix: redirect to home page after posting a highlight

src/constants.ts, src/content-scripts/components/AICodeReview/AICodeReviewMenu.ts, src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts, src/utils/checkAuthentication.ts
As explained in https://github.com/open-sauced/ai/issues/228#issuecomment-1655881541, currently users have to click the "Connect with GitHub" button on `insights.opensauced.pizza` to log into the extension due to the introduction of PKCE to the Supabase auth flow.
A redirection to the login URL won't work anymore as every login request will need to have a `code_challenge` and the `verifier` code stored as the cookie. 
This PR intends to resolve this by implementing the same.
Resolves #228. 
**CURRENT BEHAVIOUR**
**PROPOSED CHANGE**
=> feat: Login with pkce

npm-shrinkwrap.json, src/hooks/useGetGitHubPageInfo.ts, src/utils/dom-utils/prWatcher.ts
* Update npm-shrinkwrap.json to use version 7.5.4 of semver package. 
* Update useGetGitHubPageInfo.ts to check if the repository is public before setting the page type as `"REPO"`. 
* Add a new import statement for `domUpdateWatcher` in prWatcher.ts and disconnect the observer when the user navigates to a new page.
The issue of multiple buttons arises due to the instantiation of multiple mutation observers while a user navigates back and forth on pull request pages, which should be resolved now.
Additonally, as mentioned in https://github.com/open-sauced/ai/issues/217#issuecomment-1636822365, a public repository check has been added before rendering the "Add project to LinkedIn" button.
Fixes #217, #227.
**RESOLVES THE FOLLOWING …
=> fix: Multiple button injections

src/content-scripts/components/AddPRToHighlights/AddPRToHighlightsButton.ts
This PR updates the `AddPRToHighlightsButton` component in the `AddPRToHighlightsButton.ts` file. 
- The code has been formatted for better readability.
- The `onclick` event handler has been updated to toggle the visibility of the dropdown menu.
- The `addEventListener` for the `click` event has been added to hide the dropdown menu when clicking outside of it.
These changes improve the functionality and user experience of the `AddPRToHighlightsButton` component.
Fixes #242
=> fix: updated link

src/utils/checkAuthentication.ts
The extension does not currently work in Firefox. This PR does not fix that, but addresses one of the errors that occurs when trying to get the extension to work in Firefox.
Firefox supports objects with [computed property names](https://ui.dev/computed-property-names), which allows using a variable as the key, for instance:
`{ [OPEN_SAUCED_OPTED_LOG_OUT_KEY]: false }`
In Firefox, this syntax requires it to be assigned to a variable, otherwise, it throws an error.
The fix involves assigning the object with the computed property name to a variable, like this:
Then it can be used in the code, like this:
```typescript
const optedLogout = { [OPEN_SAUCED_OPTED_LOG_OUT_KEY]: false };
void chrome.storage.local.set(optedLogout);
```
To test this fix, ensure that things still behave correctly when …
=> fix: syntax error being thrown in Firefox for anonymous objects with computed property names

src/constants.ts, src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts, src/popup/pages/home.tsx, src/ts/types.ts, src/worker/background.ts
This PR fixes the infamous and long-overdue #221 by delegating the injection task to a background worker. As the current implementation using the button's `onClick` handler breaks up abruptly, causing the issue.
Additionally, adds a `popover` attribute to the AI PR description button for #254.
Resolves #254.
Resolves #221.
=> fix: linkedin projects share

.github/workflows/development.yml, .github/workflows/playwright.yml, .github/workflows/release.yml
This PR proposes to replace Node with Bun for installing dependencies in our GH workflows.
For the evident performance benefits.
Using `actions/setup-node@v2.1.5` and `bahmutov/npm-install@v1`
Using `oven-sh/setup-bun@v1`
N/A
N/A
=> ci: bun install, x

.env.development, .env.production, .env.test, .github/workflows/release.yml, manifest.json, src/popup/components/HighlightSlide.tsx
This PR fix the issue of not being able to login to the extension due the rename of insights website to app. 
I think we need to add tests as well though. 
Fixes #271
=> fix: login to the website after rename

src/constants.ts, src/content-scripts/components/ViewOnOpenSaucedButton/ViewOnOpenSaucedButton.ts, src/utils/dom-utils/viewOnOpenSauced.ts
This PR add an edge case for view on open sauced, which checks the user profile and at the same time it fixes the inconsistent space that we had. 
Note: There is extra space between the profile image and the button that could be fixed with #89. 
Closes #146 
Closes #259 
| Case | Before| After  |
|--------|--------|--------|
| Personal Profile with bio | ![image](https://github.com/open-sauced/ai/assets/18273833/58480d8c-175e-48fa-980d-caf43eaac03e)  | ![image](https://github.com/open-sauced/ai/assets/18273833/1714cede-a4ae-4058-90b6-5256ad1079b4) |
| Personal Profile without bio | ![image](https://github.com/open-sauced/ai/assets/18273833/3e27d5dc-104a-4851-a928-527145a9ca32) | ![image](https://github.com/open-sauced/ai/assets/18273833/b28c4334-b379-42b2-865c-ee87f46c7279) |
| Other …
=> fix: view on open sauced

README.md, src/constants.ts
This PR holds changes as below:
- Fixed the link to the Usage Guide in the README and `constants.ts`.
- Updated the Contributing and Community sections in the README to add more info for clarity.
- Fixed title capitalization.
Fixes #297
=> fix: Link to Usage Guide and Update README

src/constants.ts, src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts, src/content-scripts/github.ts, src/utils/ai-utils/cursorPositionInsert.ts, src/utils/dom-utils/addDescriptionGenerator.ts
This is PR is a second part of https://github.com/open-sauced/ai/pull/282, if we merge the one before we will have less edits here, did not feel to have one large PR. 
At this PR, I just enabled the AI description generator in comments and refactored the code based on that. 
Closes #283 
Closes https://github.com/open-sauced/ai/issues/288
Before: 
After:
=> feat: enable AI description generator on comments

test/api/openSaucedApi.test.ts, test/utils/urlMatcher.test.ts
Saw test were failing on a benign change on #310. This fixes the user 404 test and Tailwind's default branch change.
#310
#309 
#308 
npm test
=> fix: test driftage

.github/workflows/release.yml
There are failing release actions: https://github.com/open-sauced/ai/actions/runs/10460890612/job/28969268401 because the bot isn't able to push to `beta`. This corrects this by using the generate token step we use elsewhere.
N/a - followup to Brian's cleanup work
=> fix: Generates a token so the open-sauce bot can push to beta
