- src/content-scripts/profileScreen.ts
- src/utils/fetchOpenSaucedApiData.ts
This check will make invites matter more. Prior we were checking if we had the users data, but the goal is to invite users that have signed up to opensauced. This distinction between the two states is confusing. 
1. an opensauced user is someone who has code or a profile we have indexed. 
2. an opensauced member is someone who auth'd to opensauced and made a profile.
fixes #33
> feat: adds check for the membership

- .github/workflows/compliance.yml
Now that releases exists, this commit adds PR Compliance to require contributors to add flags to the PR titles. This is documented in the [docs](https://docs.opensauced.pizza/contributing/introduction-to-contributing/#pr-validation).
FYI @diivi @Anush008 
fixes #43
> feat: Create compliance.yml

- manifest.json
Heard back from the Chrome store. The extension was rejected due to the existence of permissions not being used. I am removing `activeTab` since we are not using it in app. 
Response from Chrome
>Use of permissions : 
>Violation: Extension is requesting chrome permission which is not used in the code.
How to rectify: Please remove chrome permission from the manifest file.
> fix: remove activeTab manifest.json

- npm-shrinkwrap.json
- package.json
- src/pages/profile.tsx
> fix: render emojis in user bio

- src/pages/profile.tsx
This PR [fixes] the [username text and avatar centered alignment bug]. 
Fixes #66
> fix: username and avatar alignment

- src/content-scripts/components/RepoVoting/RepoVoteButton.ts
- src/utils/fetchOpenSaucedApiData.ts
Voting expects a PUT request and the param to voteorunvoterepo function should be true.
> fix: incorrect request for voting

- src/content-scripts/components/RepoVoting/RepoUnvoteButton.ts
- src/content-scripts/components/RepoVoting/RepoVoteButton.ts
- src/utils/fetchOpenSaucedApiData.ts
This PR resolves the circular dependency issue in the repository vote and unvote buttons using dynamic imports, updates the `voteOrUnvote()` with a `method` param for better clarity.
> fix: circular-deps in vote buttons

- src/pages/profile.tsx
- src/utils/fetchOpenSaucedApiData.ts
This PR adds the feature #75. 
Fixes #75
> feat: replace open issues count with highlights count

- manifest.json
🎉✨Introducing OpenSauced.ai!✨🎉
This commit updates our manifest.json to reflect our new name. We're excited to continue empowering open-source contributors with our platform. Stay tuned for more updates! 🚀👨‍💻
Description generated using [OpenSauced](https://opensauced.ai/).
> feat: instant increase in valuation

- src/utils/aiprdescription/cursorPositionInsert.ts
This pull request adds a small tweak to the AI-generated descriptions in our text editor. Now, there will be an extra line break before the description. Why? Because we like our code to have room to breathe! Plus, we've updated the explanatory text to include a link to OpenSauced - check it out and give us your feedback!
_Description generated using [OpenSauced](https://opensauced.ai/)._
> fix: add extra line and italics

- npm-shrinkwrap.json
- package.json
- src/App.tsx
- src/main.tsx
- src/pages/aiprdescription.tsx
- src/pages/home.tsx
- src/pages/loading.tsx
- src/pages/profile.tsx
This PR updates the extension dropdown navigation using the [`react-chrome-extension-router`](https://npm.io/package/react-chrome-extension-router) package that results in improved code readability and offers a simplified navigation solution for future pages. Additionally, it eliminates the need for a React context provider and consumer for navigation and prop-passing purposes. This pull request is based on the suggestion from @doaortu.
[Original suggestion](https://github.com/open-sauced/ai/pull/36#issue-1684347376)
No visual changes.
> refactor: improved-extension-navigation

- src/content-scripts/components/AICodeRefactor/ChangeSuggestorButton.ts
- src/utils/dom-utils/changeSuggestorButton.ts
- src/utils/dom-utils/prWatcher.ts
> fix: showing the icon

- src/pages/home.tsx
- src/pages/start.tsx
This PR updates the text on the Home and Start pages for better user experience. The "Go to Highlights feed" and "Go to Dashboard" buttons now simply say "Highlights feed" and "Dashboard" respectively, since we already have the "Go to" icon right next to them. Additionally, the "AI PR Description" button has been renamed to "AI Content Configuration", because we use that tab for other AI configuration too. The "Login!" button on the Start page has also been updated to simply say "Login".
> chore: update text for home links

- src/constants.ts
- src/content-scripts/components/AddPRToHighlights/AddPRToHighlightsButton.ts
- src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts
- src/content-scripts/components/InviteToOpenSauced/InviteToOpenSaucedButton.ts
- src/content-scripts/components/RepoVoting/RepoUnvoteButton.ts
- src/content-scripts/components/RepoVoting/RepoVoteButton.ts
- src/content-scripts/components/ViewOnOpenSaucedButton/ViewOnOpenSaucedButton.ts
- src/pages/start.tsx
- src/utils/dom-utils/addDescriptionGenerator.ts
- src/utils/dom-utils/addPRToHighlights.ts
- src/utils/dom-utils/inviteToOpenSauced.ts
- src/utils/dom-utils/repoVotingButtons.ts
- src/utils/dom-utils/viewOnOpenSauced.ts
As suggested in https://github.com/open-sauced/ai/pull/107#issuecomment-1559786936, this PR resolves the duplicate button injection issue mentioned in #87 by updating the injection guards used in the project. 2a9eced46ad99584a97ce89644a1d7c23c743c44.
Additionally, this PR, 
* Adds background-color, padding to the extension login page. 00b214820d27c59a324507b100333517a99f1835.
* As mentioned in https://github.com/open-sauced/ai/pull/101#issuecomment-1559198667, removes the PR author check before injecting the "Add PR to highlights" button. 5e1869205bf1eba7b247d268e10dca896994fdb8.
Resolves #87.
> fix: duplicate-button-injections using guards

- src/content-scripts/github.ts
The vote feature is bugged and I have not been able to leverage it consistently. With the product focused around AI and drawing installs, it is not ideal to have the vote feature live until it is figured out.
This PR comments out the `injectRepoVotingButtons` function in `github.ts` as it is not ready yet and causes issues. This will prevent any errors from occurring until the issue is resolved.
https://github.com/open-sauced/ai/issues/106
> feat: Remove the vote feature temporarily

- src/constants.ts
- src/utils/dom-utils/viewOnOpenSauced.ts
This PR fixes the bug #97 . 
Fixes #97
> fix: view button location

- README.md
- docs/0-introduction.md
- docs/1-folder-structure.md
- docs/2-adding-a-new-component.md
- src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts
Added developer documentation. For now, it explains 
#67
> docs: dev docs

- .github/workflows/development.yml
This PR adds a new GitHub workflow file for Development. The workflow is triggered on pull_request events with types: opened, edited, synchronize, and reopened. The workflow includes a single job named "test" that uses the open-sauced/hot/.github/workflows/development.yml@main action.
> feat: adds test and lint to build

- .gitignore
- npm-shrinkwrap.json
- package.json
- test/utils/dateUtils.test.ts
- test/utils/urlMatcher.test.ts
Builds a base for all tests ( solving #114 )
> test: setup tests

- .github/workflows/development.yml
🚀 Exciting news! This PR updates our development workflow to use Node.js v18 and the latest version of npm. We've also added steps to checkout the repository and install dependencies using bahmutov/npm-install. This will ensure a smooth build process and faster development. Let's merge and enjoy the benefits! 🎉
I added https://github.com/open-sauced/ai/pull/127 to add a build check but never set up a node environment for the build to run.
fixes #144
> fix: build for workflows

- src/pages/help.tsx
- src/pages/home.tsx
- src/vite-env.d.ts
- vite.config.ts
Added the version of the extension on the home page and declared config as global value for the extension. 
closes #125 
Closes #125 
npm run dev:
> chore: display version on the extension.

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/popup.css
- src/popup/components/HighlightSlide.tsx
- src/popup/pages/aiprdescription.tsx
- src/popup/pages/home.tsx
- src/popup/pages/posthighlight.tsx
- src/utils/fetchOpenSaucedApiData.ts
This PR includes a carousel design for the highlights feed (#173) with uniform heights and a11y navigation pagination. Additionally, a user feedback has been added in case of an error (#171). The package has been linted and updated, and a minor release 1.6.0-beta.1 has been made on the beta channel.
> v1.6.0-beta.1 -> main

- src/popup/components/ToggleSwitch.tsx
- src/popup/pages/aiprdescription.tsx
- src/popup/pages/home.tsx
- src/popup/pages/settings.tsx
This PR updates the UI of the AI configuration page and removes the button from the home page. It also adds the AI configuration page to the settings page. The "Save" button on the AI configuration page is now more descriptive. The changes improve the user experience and make the UI more consistent.
part of #179
> refactor: move ai config to settings

- src/popup/pages/home.tsx
> refactor: remove link to dashboard

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/constants.ts
- src/popup/components/HighlightSlide.tsx
- src/popup/components/ToggleSwitch.tsx
- src/popup/pages/aiprdescription.tsx
- src/popup/pages/home.tsx
- src/popup/pages/settings.tsx
- src/ts/types.ts
- src/utils/fetchOpenSaucedApiData.ts
This PR includes code refactoring and a new feature. The ai config has been moved to settings and the link to the dashboard has been removed. Additionally, a new feature has been added to show highlight reactions. This PR also includes beta releases 1.7.1-beta.1, 1.7.1-beta.2, and 1.8.0-beta.1.
> v1.8.0-beta.1 -> main

- npm-shrinkwrap.json
- package.json
- src/utils/getUserPRVelocity.ts
- test/utils/colorPreference.test.ts
- test/utils/getUserPRVelocity.test.ts
- vite.config.ts
What type of PR is this? (check all applicable)
-----------------------------------------------
-   [ ]  🍕 Feature
-   [ ]  🐛 Bug Fix
-   [ ]  📝 Documentation Update
-   [ ]  🎨 Style
-   [ ]  🧑‍💻 Code Refactor
-   [ ]  🔥 Performance Improvements
-   [x]  ✅ Test
-   [ ]  🤖 Build
-   [ ]  🔁 CI
-   [ ]  📦 Chore (Release)
-   [ ]  ⏩ Revert
Description
-----------
This PR is related to [Write tests for utility functions #188](https://github.com/open-sauced/ai/issues/188) and adds tests for the following files:
- src/utils/colorPreference.ts
- src/utils/getUserPRVelocity.ts
In order to work with window object, modifications were made to the Vite config, setting the environment to 'jsdom',
No other files or tests were changed or affected.
Related Tickets & Documents
--------------------------- …
> test: Tests for colorPreference and getUserPRVelocity

- docs/project-utilities.md
This PR moves project utilities to the docs folder.
Fixes issue #166
closes #201
No
> feat: Cherry pick susmita

- src/utils/ai-utils/descriptionconfig.ts
Change the default tone from informative to formal
Closes #210
> feat: make formal the default tone

- src/popup/pages/home.tsx
> fix: post highlights from the extension

- src/constants.ts
- src/content-scripts/components/ViewOnOpenSaucedButton/ViewOnOpenSaucedButton.ts
- src/utils/dom-utils/viewOnOpenSauced.ts
changed the unique identifier from bio to the whole profile editable section and added the "View on Opensauced" button  on top of it. 
[bug-fix] Fix the location of "View on OpenSauced" button on GitHub profile page
This PR fixes the location of the "View on OpenSauced" button on the GitHub profile page. Previously, the button was not displayed correctly due to a CSS class issue. This PR updates the CSS class name to match the constant name, ensuring that the button is displayed in the correct position.
Additionally, this PR removes unwanted lint changes in the constants file and changes the variable name for better clarity.
Fixes #146
- [✅ ] 🙅 no, because they aren't needed
- [ ✅] 🙅 no documentation needed
> fix: view on open sauced location

- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- src/constants.ts
- src/content-scripts/components/AICodeReview/AICodeReviewMenu.ts
- src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts
- src/content-scripts/components/ViewOnOpenSaucedButton/ViewOnOpenSaucedButton.ts
- src/hooks/useGetGitHubPageInfo.ts
- src/popup/pages/home.tsx
- src/popup/pages/posthighlight.tsx
- src/utils/checkAuthentication.ts
- src/utils/dom-utils/viewOnOpenSauced.ts
- src/utils/fetchOpenSaucedApiData.ts
This pull request introduces the following changes:
- Added the feature to view repositories on opensauced (#218)
- Fixed a bug where the extension was not redirecting to the home page after posting a highlight (#203)
- Added a forceRefresh parameter to force cache invalidation
- feat: Login with pkce (#230)
- Made some minor fixes and improvements
For more details, please refer to the commit messages and the linked issues.
> main <- v1.12.0-beta.5

- src/utils/colorPreference.ts
Added optional chaining operator to prevent extension from throwing an error when not logged in and viewing a repo (when color_mode cookie is not set).
Fixes #240 
#240
> fix: prevent error when viewing repo and not logged in

- src/popup/components/HighlightSlide.tsx
This PR checks if the title is available or not, if it's not available, it will hide it. 
fixes #266
Before: 
After:
> fix: hide title when not available

- src/constants.ts
- src/content-scripts/components/AICodeReview/AICodeReviewMenu.ts
- src/content-scripts/components/GenerateAIDescription/DescriptionGeneratorButton.ts
- src/utils/dom-utils/addPRToHighlights.ts
- src/utils/dom-utils/changeSuggestorButton.ts
This PR fixes the constant naming. Renamed all of the content-scripts classes.
Fixes #281
> feat: refactor constant naming

- src/repo-query/pages/chat.tsx
This PR enables the Chat component to run by handling the expected data. 
fixes #287
https://github.com/open-sauced/ai/assets/18273833/d804db67-f5bd-41f1-ab88-5effec796a43
https://github.com/open-sauced/ai/assets/18273833/17e462bb-f2c2-433d-afe3-b0bdc02d8b75
> fix: chunk processing in Chat component

- .gitattributes
Windows users encounter lint error of `Expected linebreaks to be 'LF' but found 'CRLF'` because the default behavior of git on Windows systems is to convert LF linebreaks to CRLF when checking out files, but to store the linebreaks as LF when committing a change.
This PR adds a `.gitattributes` file and normalize all line endings in `.ts` files to make it easy for developers to contribute from different platforms.
Fixes #299 
No more `Expected linebreaks to be 'LF' but found 'CRLF'` error in `.ts` and `.tsx` files.
> fix: add `.gitattributes` file and normalize all the line endings

- .env.development
- .env.production
- .env.test
Upgrades env vars to v2 API
---
⚠️ Note! We'll likely want to hold off on merging this until the actual cutover for the API v1 --> v2 happens!
Related to: https://github.com/open-sauced/ai/issues/302
Related to: https://github.com/open-sauced/api/issues/478
Went through the code and there's nothing that was touched with the API generation endpoints - could use help here to further validate if needed.
> feat: Upgrade to v2 API

- .github/workflows/release.yml
Fixes some broken yamls in the release github action: https://github.com/open-sauced/ai/actions/runs/10474945427
Followup to: https://github.com/open-sauced/ai/pull/313
Needed by: https://github.com/open-sauced/ai/pull/314
> chore: Fix broken GitHub release workflow
